# 服务器配置
server:
  port: 9001

# 数据库配置
spring:
  application:
    name: security-admin
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/admin?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  # Flyway 数据库迁移配置
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history_admin
    out-of-order: true
    validate-on-migrate: false

  # OAuth2 资源服务器配置
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:https://885ro126ov70.vicp.fun}
      client:
        registration:
          webapp-client:
            client-id: webapp-client
#            client-secret: webapp-secret
            authorization-grant-type: authorization_code
            scope: read,write,openid,profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            # PKCE和Basic认证共存配置
            client-authentication-method: none
        provider:
          webapp-client:
            # issuer-uri: ${ISSUER_URI:https://885ro126ov70.vicp.fun}
            authorization-uri: https://885ro126ov70.vicp.fun/oauth2/authorize
            token-uri: https://885ro126ov70.vicp.fun/oauth2/token
            jwk-set-uri: https://885ro126ov70.vicp.fun/oauth2/jwks
            user-info-uri: https://885ro126ov70.vicp.fun/userinfo
# 自定义配置
webapp:
  oauth2:
    enable-pkce: true # 默认禁用PKCE，使用Basic认证
    # 可以通过环境变量启用: -Dwebapp.oauth2.enable-pkce=true

# 日志配置
logging:
  level:
    root: INFO
    com.webapp: DEBUG
    org.springframework.security: DEBUG # 提高安全相关日志级别，方便调试
    com.baomidou.mybatisplus: DEBUG
    org.springframework.web: DEBUG # 添加Web相关日志，方便调试请求/响应


